GCP_PROJECT = "msca310019-capstone-f945"

# Article Ingestion
ARTICLE_TARGET_BUCKET = "consolidated-articles"
ARTICLE_CONVERT_META_BUCKET = "meta-info"
ARTICLE_CONVERT_META_IDX = "scraper-markdown-index.json"
ARTICLE_BUCKET_IDX = "index.json"
ARTICLE_CONVERT_CHUNK = 100
ARTICLE_CONVERT_CNBC_DATE = "%Y-%m-%dT%H:%M:%S%z"
ARTICLE_CONVERT_REUTER_DATE = "%B %d, %Y %I:%M %p"
ARTICLE_CONVERT_NYT_DATE = "%Y-%m-%dT%H:%M:%S%z"
ARTICLE_CONVERT_SUBSAMPLE_TARGET = "scraped-news-article-data-null"
ARTICLE_CONVERT_SUBSAMPLE_FILE = "subsample-{year}-{month}.parquet"
ARTICLE_CONVERT_SUBSAMPLE_IDX = "scraper-subsample.json"

# Fine-tuning Ingestion
FINE_TUNE_TARGET_BUCKET = "scraped-news-article-data-null"
FINE_TUNE_FILE_PATTERN = "fine-tune-summary-{split}.parquet"
FINE_TUNE_FILE_CHUNK = 64

# Co-reference Resolution
ARTICLE_COREF_SRC_BUCKET = ARTICLE_CONVERT_SUBSAMPLE_TARGET
ARTICLE_COREF_MOD_URL = "https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2021.03.10.tar.gz"
ARTICLE_COREF_SPACY_MOD = "en_core_web_sm"
ARTICLE_COREF_TARGET_BUCKET = ARTICLE_CONVERT_SUBSAMPLE_TARGET
ARTICLE_COREF_FILE_PATTERN = "corref-{year}-{month}.parquet"

# Topic Extraction
TOPIC_EMBEDDING = "all-MiniLM-L6-v2"
TOPIC_UMAP_NEIGHBORS = 15
TOPIC_UMAP_COMPONENTS = 5
TOPIC_UMAP_MIN_DIST = 0
TOPIC_UMAP_METRIC = "euclidean"
TOPIC_HDBSCAN_MIN_SIZE = 5
TOPIC_HDBSCAN_METRIC = "euclidean"
TOPIC_SUBSAMPLE_TARGET = ARTICLE_CONVERT_SUBSAMPLE_TARGET
TOPIC_SUBSAMPLE_FILE = "topic-{year}-{month}.parquet"

# Topic Summarization
TOPIC_SUM_KIND = "openai"
TOPIC_SUM_MODEL_PARAMS = {
    "api_key": "../key"
}
TOPIC_SUM_TARGET = "scraped-news-article-data-null"
TOPIC_SUM_TARGET_FILE = "topicsum-{year}-{month}.parquet"

# NER
NER_SPACY_MOD = "en_core_web_md"

# FAISS Articles
ARTICLE_FAISS_TEMP_DIRECTORY = "./article_db"
ARTICLE_FAISS_EMBEDDING = "thenlper/gte-base"
ARTICLE_DB_COLLECTION = "articles"
TOPICS_DB_COLLECTION = "topics"
ARTICLE_FAISS_TARGET = "scraped-news-article-data-null"
ARTICLE_FAISS_FILE = "article-chroma-{year}-{month}.zip"
ARTICLE_FAISS_BATCH = 16
ARTICLE_FAISS_PROCESSES = None

# FAISS Topics
TOPIC_FAISS_EMBEDDING = ARTICLE_FAISS_EMBEDDING
TOPIC_FAISS_TARGET = "scraped-news-article-data-null"
TOPIC_FAISS_FILE = "topic-chroma-{year}-{month}.zip"
TOPIC_FAISS_BATCH = 16

# AI Assisted Summary Augmentation
VERTEX_AI_KEY_PATH = "../nlp-final-386206-e7043b88437d.json"
VERTEX_AI_PROJECT = "nlp-final-386206"
SUMMARY_AUG_SYSTEM = "You are a helpful AI assistant that will come up with a good question that can be answered by the given text, " \
                     "and a good question that cannot be answered by the text. "\
                     "The answer to the answerable question must be from the information in the provided text. " \
                     "The question must be something that a retail investor is likely going to ask. " \
                     "The output should be formatted as:\n" +\
                     """Response:
REASON (Unanswerable): reason why a retail investor would ask the question that cannot be answered.
UNANSWERABLE: reason why the question cannot be answered with only information from the text.
QUESTION (Unanswerable): the unanswerable question.

REASON (answerable): reason why a retail investor would ask the question that can be answered.
ANSWER: answer to the answerable question from the text.
QUESTION (answerable): the answerable question.

An example:
Text: 
Anthropic’s AI chatbot Claude is posting lyrics to popular songs, lawsuit claims
* Universal Music has sued Anthropic, the AI startup, over “systematic and widespread infringement of their copyrighted song lyrics,” per a filing Wednesday in a Tennessee federal court.
* Anthropic, the $4.1 billion startup behind Claude the chatbot, was founded in 2021 by former OpenAI research executives.
* Other music publishers, such as Concord and ABKCO, were also named as plaintiffs
Response:

REASON (Unanswerable): Retail investors would want to estimate the potential financial repercussions of the lawsuit on Anthropic in order to assess the company's financial stability and investment prospects.
UNANSWERABLE: The text only mention that a lawsuit occurred, but does not mention any specific consequences of the lawsuit
QUESTION: What potential financial damages or penalties is Anthropic facing as a result of the lawsuit filed by Universal Music and other plaintiffs?

REASON: Since the AI industry and Anthropic are both relatively new, retail investors may want to understand the regulatory and legal risks associated before making any move.
ANSWER: Anthropic is being sued by music publishers including Universal Music, Concord, and ABKCO over copyrighted lyrics generated by Claude.
QUESTION: What are some legal risks that Anthropic is currently facing?

Follow the example. Begin.
"""
SUMMARY_AUG_USER = "{input_text}"
SUMMARY_AUG_PARSE_SYSTEM = "You are a helpful AI assistant that will convert natural language into a machine parsable format. {format_instructions}"
SUMMARY_AUG_PARSE_EXAMPLE = {"raw": """REASON (Unanswerable): Retail investors would want to estimate the potential financial repercussions of the lawsuit on Anthropic in order to assess the company's financial stability and investment prospects.
UNANSWERABLE: The text only mention that a lawsuit occurred, but does not mention any specific consequences of the lawsuit
QUESTION: What potential financial damages or penalties is Anthropic facing as a result of the lawsuit filed by Universal Music and other plaintiffs?

REASON: Since the AI industry and Anthropic are both relatively new, retail investors may want to understand the regulatory and legal risks associated before making any move.
ANSWER: Anthropic is being sued by music publishers including Universal Music, Concord, and ABKCO over copyrighted lyrics generated by Claude.
QUESTION: What are some legal risks that Anthropic is currently facing?""",
                             "output": """{"answerable": "What are some legal risks that Anthropic is currently facing?", "unanswerable": "What potential financial damages or penalties is Anthropic facing as a result of the lawsuit filed by Universal Music and other plaintiffs?"}"""}
SUMMARY_AUG_PARSE_USER = "{text}"
SUMMARY_AUG_MODEL = "chat-bison"
SUMMARY_AUG_TEMPERATURE = 0
