FROM python:3.10.13-bullseye

ENV PYTHONUNBUFFERED True
ENV APP_HOME /FinBot
WORKDIR $APP_HOME

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install streamlit elasticsearch sentence-transformers langchain tiktoken openai pstock-python httpx
RUN pip install plotly google-cloud-aiplatform spacy nltk
RUN python -m spacy download en_core_web_sm

COPY ./es_id ./es_key ./key $APP_HOME/
ADD ./summarizer $APP_HOME/summarizer
COPY ./dashboardv4.py $APP_HOME/

ENTRYPOINT streamlit run --server.port 80 dashboardv4.py

