FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel

ENV PYTHONUNBUFFERED True
ENV APP_HOME /FinBot
ENV PORT 80
WORKDIR $APP_HOME

RUN apt-get update && apt-get install build-essential -y
RUN pip install vllm transformers fschat accelerate
EXPOSE $PORT
ENTRYPOINT python -m vllm.entrypoints.openai.api_server --model databricks/dolly-v2-3b --dtype float16 --port $PORT