FROM python:3-bullseye

ENV PYTHONUNBUFFERED True
ENV APP_HOME /FinBot
WORKDIR $APP_HOME

COPY ./scraper/common.py ./scraper/cnbc_requests.py ./
RUN pip install unstructured lxml nltk schedule fake-useragent beautifulsoup4 requests google-cloud-storage google-cloud-logging google-cloud-bigquery pydantic google-cloud-bigquery-storage

RUN python -c "import unstructured"

ENTRYPOINT ["python", "cnbc_requests.py"]
